services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ~/Downloads:/Downloads
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
