services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  converter:
    build:
      context: ./converter
      dockerfile: Dockerfile
    ports:
      - 8080:8080
