name: API Continuous Integration
on:
  push:
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

defaults:
  run:
    working-directory: ./api

jobs:
  ci:
    name: Build, test, and lint backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Verify formatting
        run: |
          set -euo pipefail

          make fmt

          DIFF=$(git status --porcelain)

          if [ -n "$DIFF" ]; then
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.4
          working-directory: ./api
