name: Web Continuous Integration
on:
  push:
    paths:
      - 'web/**'
  pull_request:
    paths:
      - 'web/**'

defaults:
  run:
    working-directory: ./web

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Build and lint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
